# Project: lr-3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = lr-3.o
LINKOBJ  = lr-3.o
LIBS     = -L"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/lib" -L"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = lr-3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

lr-3.o: lr-3.cpp
	$(CPP) -c lr-3.cpp -o lr-3.o $(CXXFLAGS)
