# Project: lr--1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = lr--1.o lr--2.o
LINKOBJ  = lr--1.o lr--2.o
LIBS     = -L"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/lib" -L"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Hafeez/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = lr--1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

lr--1.o: lr--1.cpp
	$(CPP) -c lr--1.cpp -o lr--1.o $(CXXFLAGS)

lr--2.o: lr--2.cpp
	$(CPP) -c lr--2.cpp -o lr--2.o $(CXXFLAGS)
